name: A workflow for test automationin MLOps 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: project-testing
        run: |
          pip install -r requirements.txt
          echo "::set-env name=PYTHONPATH::home/runner/work/TDD-in-MLOps"
          pytest tests/
          
