name: A workflow for test automationin MLOps 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dcvorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: project-test

      run:
        python setup.py sdist bdist_wheel
        pip install -e .
        pytest