name: A workflow for test automationin MLOps 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: project-testing
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          echo "::set-env name=PYTHONPATH::home/runner/work/TDD-in-MLOps/src"
          pip install -r requirements.txt
          pytest tests/
          
